#pragma once
#include "CoreMinimal.h"
#include "StructUtils/InstancedStruct.h"
#include "FCrowdyEntitySpawnEvent.generated.h"

// Someone spawned an object
USTRUCT(BlueprintType, meta=(CrowdyRep="Event"))
struct FCrowdyEntitySpawnEvent
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FGuid EntityID;          // Generated by spawner, permanent identity

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FGuid OwnerID;           // Who created it

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int32 TypeID = 0;        // Maps to registry entry → actor class + handler

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FTransform SpawnTransform;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FInstancedStruct InitialState;  // Type-specific initial data (boss level, cube color, etc.)
};

// Someone changed object state
USTRUCT(BlueprintType, meta=(CrowdyRep="Event"))
struct FCrowdyEntityStateEvent
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FGuid EntityID;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FInstancedStruct NewState;
};

// Someone destroyed an object
USTRUCT(BlueprintType, meta=(CrowdyRep="Event"))
struct FCrowdyEntityDestroyEvent
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FGuid EntityID;
};