#pragma once
#include "CoreMinimal.h"
#include "StructUtils/InstancedStruct.h"
#include "FCrowdyEntitySpawnEvent.generated.h"

// Someone spawned an object
USTRUCT(BlueprintType)
struct FCrowdyEntitySpawnEvent
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FGuid EntityID;          // Generated by spawner, permanent identity

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FGuid OwnerID;           // Who created it

	// Hash of the entity class path; receivers resolve it through
	// UCrowdyClassRegistry. Not Blueprint-exposed (uint32).
	UPROPERTY(EditAnywhere)
	uint32 ClassID = 0;

	// Fallback when the receiver doesn't know ClassID (e.g. a Blueprint class
	// that wasn't loaded during its startup scan). Also useful for debugging.
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString ClassPath;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FTransform SpawnTransform;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FInstancedStruct InitialState;  // Type-specific initial data (boss level, cube color, etc.)
};

// Someone destroyed an object
USTRUCT(BlueprintType)
struct FCrowdyEntityDestroyEvent
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FGuid EntityID;
};