#pragma once
#include "CoreMinimal.h"
#include "EVoxelType.generated.h"

UENUM(BlueprintType)
enum class EVoxelType : uint8
{
	// 0-9: Base Colors and Neutrals
    AIR = 0                      UMETA(DisplayName = "Empty voxel"),
    RED = 1                      UMETA(DisplayName = "Red voxel"),
    GREEN = 2                    UMETA(DisplayName = "Green voxel"),
    BLUE = 3                     UMETA(DisplayName = "Blue voxel"),
    YELLOW = 4                   UMETA(DisplayName = "Yellow voxel"),
    ORANGE = 5                   UMETA(DisplayName = "Orange voxel"),
    GREY = 6                     UMETA(DisplayName = "Grey voxel"),
    PURPLE = 7                   UMETA(DisplayName = "Purple voxel"),
    BROWN = 8                    UMETA(DisplayName = "Brown voxel"),
    WHITE = 9                    UMETA(DisplayName = "White voxel"),

    
    // 10-29: Red Family
    DARK_RED = 10                UMETA(DisplayName = "Dark Red voxel"),
    CRIMSON = 11                 UMETA(DisplayName = "Crimson voxel"),
    MAROON = 12                  UMETA(DisplayName = "Maroon voxel"),
    BLOOD_RED = 13               UMETA(DisplayName = "Blood Red voxel"),
    RUST_RED = 14                UMETA(DisplayName = "Rust Red voxel"),
    LIGHT_RED = 15               UMETA(DisplayName = "Light Red voxel"),
    TORINO_RED = 16				 UMETA(DisplayName = "Torino Red voxel"),
    CARDINAL = 17                UMETA(DisplayName = "Cardinal Red voxel"),
    CHERRY_RED = 18              UMETA(DisplayName = "Cherry Red voxel"),
    TOMATO_RED = 19              UMETA(DisplayName = "Tomato Red voxel"),
    SALMON_RED = 20              UMETA(DisplayName = "Salmon Red voxel"),
    CORAL_RED = 21               UMETA(DisplayName = "Coral Red voxel"),
    INDIAN_RED = 22              UMETA(DisplayName = "Indian Red voxel"),
    BRICK_RED = 23               UMETA(DisplayName = "Brick Red voxel"),
    VERMILION = 24               UMETA(DisplayName = "Vermilion voxel"),
    FIRE_ENGINE_RED = 25         UMETA(DisplayName = "Fire Engine Red voxel"),
    RUBY_RED = 26                UMETA(DisplayName = "Ruby Red voxel"),
    BARN_RED = 27                UMETA(DisplayName = "Barn Red voxel"),
    CHILI_PEPPER_RED = 28        UMETA(DisplayName = "Chili Pepper Red voxel"),
    CINNABAR = 29                UMETA(DisplayName = "Cinnabar voxel"),

    // 30-49: Green Family
    FOREST_GREEN = 30            UMETA(DisplayName = "Forest Green voxel"),
    LIME_GREEN = 31              UMETA(DisplayName = "Lime Green voxel"),
    DARK_GREEN = 32              UMETA(DisplayName = "Dark Green voxel"),
    OLIVE_GREEN = 33             UMETA(DisplayName = "Olive Green voxel"),
    SAGE_GREEN = 34              UMETA(DisplayName = "Sage Green voxel"),
    EMERALD_GREEN = 35           UMETA(DisplayName = "Emerald Green voxel"),
    MINT_GREEN = 36              UMETA(DisplayName = "Mint Green voxel"),
    HUNTER_GREEN = 37            UMETA(DisplayName = "Hunter Green voxel"),
    SEA_GREEN = 38               UMETA(DisplayName = "Sea Green voxel"),
    KELLY_GREEN = 39             UMETA(DisplayName = "Kelly Green voxel"),
    APPLE_GREEN = 40             UMETA(DisplayName = "Apple Green voxel"),
    JADE_GREEN = 41              UMETA(DisplayName = "Jade Green voxel"),
    PINE_GREEN = 42              UMETA(DisplayName = "Pine Green voxel"),
    MOSS_GREEN = 43              UMETA(DisplayName = "Moss Green voxel"),
    FERN_GREEN = 44              UMETA(DisplayName = "Fern Green voxel"),
    ARMY_GREEN = 45              UMETA(DisplayName = "Army Green voxel"),
    TEA_GREEN = 46               UMETA(DisplayName = "Tea Green voxel"),
    SHAMROCK_GREEN = 47          UMETA(DisplayName = "Shamrock Green voxel"),
    ASPARAGUS_GREEN = 48         UMETA(DisplayName = "Asparagus Green voxel"),
    SEAFOAM_GREEN = 49           UMETA(DisplayName = "Seafoam Green voxel"),

   // 50-69: Blue Family
    NAVY_BLUE = 50               UMETA(DisplayName = "Navy Blue voxel"),
    SKY_BLUE = 51                UMETA(DisplayName = "Sky Blue voxel"),
    ROYAL_BLUE = 52              UMETA(DisplayName = "Royal Blue voxel"),
    TURQUOISE = 53               UMETA(DisplayName = "Turquoise voxel"),
    POWDER_BLUE = 54             UMETA(DisplayName = "Powder Blue voxel"),
    STEEL_BLUE = 55              UMETA(DisplayName = "Steel Blue voxel"),
    BABY_BLUE = 56               UMETA(DisplayName = "Baby Blue voxel"),
    CORNFLOWER_BLUE = 57         UMETA(DisplayName = "Cornflower Blue voxel"),
    INDIGO_BLUE = 58             UMETA(DisplayName = "Indigo Blue voxel"),
    MIDNIGHT_BLUE = 59           UMETA(DisplayName = "Midnight Blue voxel"),
    AZURE = 60                   UMETA(DisplayName = "Azure voxel"),
    PERIWINKLE = 61              UMETA(DisplayName = "Periwinkle voxel"),
    DENIM_BLUE = 62              UMETA(DisplayName = "Denim Blue voxel"),
    TEAL = 63                    UMETA(DisplayName = "Teal voxel"),
    PEACOCK_BLUE = 64            UMETA(DisplayName = "Peacock Blue voxel"),
    SAPPHIRE_BLUE = 65           UMETA(DisplayName = "Sapphire Blue voxel"),
    SLATE_BLUE = 66              UMETA(DisplayName = "Slate Blue voxel"),
    CYAN = 67                    UMETA(DisplayName = "Cyan voxel"),
    ARCTIC_BLUE = 68             UMETA(DisplayName = "Arctic Blue voxel"),
    MARINE_BLUE = 69             UMETA(DisplayName = "Marine Blue voxel"),

     // 70-89: Yellow and Orange Family
    GOLD = 70                    UMETA(DisplayName = "Gold voxel"),
    MUSTARD_YELLOW = 71          UMETA(DisplayName = "Mustard Yellow voxel"),
    AMBER = 72                   UMETA(DisplayName = "Amber voxel"),
    DARK_ORANGE = 73             UMETA(DisplayName = "Dark Orange voxel"),
    LIGHT_ORANGE = 74            UMETA(DisplayName = "Light Orange voxel"),
    MARIGOLD = 75                UMETA(DisplayName = "Marigold voxel"),
    HONEY = 76                   UMETA(DisplayName = "Honey voxel"),
    SUNFLOWER = 77               UMETA(DisplayName = "Sunflower voxel"),
    PUMPKIN = 78                 UMETA(DisplayName = "Pumpkin voxel"),
    TANGERINE = 79               UMETA(DisplayName = "Tangerine voxel"),
    BUTTERSCOTCH = 80            UMETA(DisplayName = "Butterscotch voxel"),
    APRICOT = 81                 UMETA(DisplayName = "Apricot voxel"),
    SAFFRON = 82                 UMETA(DisplayName = "Saffron voxel"),
    OCHRE = 83                   UMETA(DisplayName = "Ochre voxel"),
    COPPER = 84                  UMETA(DisplayName = "Copper voxel"),
    BRONZE = 85                  UMETA(DisplayName = "Bronze voxel"),
    RUST_ORANGE = 86             UMETA(DisplayName = "Rust Orange voxel"),
    TIGERS_EYE = 87              UMETA(DisplayName = "Tiger's Eye voxel"),
    CARAMEL = 88                 UMETA(DisplayName = "Caramel voxel"),
    CANTALOUPE = 89              UMETA(DisplayName = "Cantaloupe voxel"),

    // 90-109: Purple Family
    LAVENDER = 90                UMETA(DisplayName = "Lavender voxel"),
    PLUM = 91                    UMETA(DisplayName = "Plum voxel"),
    VIOLET = 92                  UMETA(DisplayName = "Violet voxel"),
    MAGENTA = 93                 UMETA(DisplayName = "Magenta voxel"),
    ORCHID = 94                  UMETA(DisplayName = "Orchid voxel"),
    GRAPE = 95                   UMETA(DisplayName = "Grape voxel"),
    LILAC = 96                   UMETA(DisplayName = "Lilac voxel"),
    EGGPLANT = 97                UMETA(DisplayName = "Eggplant voxel"),
    DEEP_PURPLE = 98             UMETA(DisplayName = "Deep Purple voxel"),
    HELIOTROPE = 99              UMETA(DisplayName = "Heliotrope voxel"),
    MAUVE = 100                  UMETA(DisplayName = "Mauve voxel"),
    THISTLE = 101                UMETA(DisplayName = "Thistle voxel"),
    AMETHYST = 102               UMETA(DisplayName = "Amethyst voxel"),
    ROYAL_PURPLE = 103           UMETA(DisplayName = "Royal Purple voxel"),
    WINE = 104                   UMETA(DisplayName = "Wine voxel"),
    MULBERRY = 105               UMETA(DisplayName = "Mulberry voxel"),
    PERIWINKLE_PURPLE = 106      UMETA(DisplayName = "Periwinkle Purple voxel"),
    BOYSENBERRY = 107            UMETA(DisplayName = "Boysenberry voxel"),
    DARK_LAVENDER = 108          UMETA(DisplayName = "Dark Lavender voxel"),
    INDIGO_PURPLE = 109          UMETA(DisplayName = "Indigo Purple voxel"),

    // 110-129: Brown Family
    CHOCOLATE = 110              UMETA(DisplayName = "Chocolate voxel"),
    COFFEE = 111                 UMETA(DisplayName = "Coffee voxel"),
    TAN = 112                    UMETA(DisplayName = "Tan voxel"),
    KHAKI = 113                  UMETA(DisplayName = "Khaki voxel"),
    SIENNA = 114                 UMETA(DisplayName = "Sienna voxel"),
    WOOD_BROWN = 115             UMETA(DisplayName = "Wood Brown voxel"),
    SANDY_BROWN = 116            UMETA(DisplayName = "Sandy Brown voxel"),
    PERU = 117                   UMETA(DisplayName = "Peru voxel"),
    LIGHT_BROWN = 118            UMETA(DisplayName = "Light Brown voxel"),
    DARK_BROWN = 119             UMETA(DisplayName = "Dark Brown voxel"),
    CHESTNUT = 120               UMETA(DisplayName = "Chestnut voxel"),
    WALNUT = 121                 UMETA(DisplayName = "Walnut voxel"),
    SEPIA = 122                  UMETA(DisplayName = "Sepia voxel"),
    BURNT_SIENNA = 123           UMETA(DisplayName = "Burnt Sienna voxel"),
    CAMEL = 124                  UMETA(DisplayName = "Camel voxel"),
    CINNAMON = 125               UMETA(DisplayName = "Cinnamon voxel"),
    NUTMEG = 126                 UMETA(DisplayName = "Nutmeg voxel"),
    CEDAR = 127                  UMETA(DisplayName = "Cedar voxel"),
    MOCHA = 128                  UMETA(DisplayName = "Mocha voxel"),
    HICKORY = 129                UMETA(DisplayName = "Hickory voxel"),

    // 130-149: Grey Family
    CHARCOAL = 130               UMETA(DisplayName = "Charcoal voxel"),
    SILVER = 131                 UMETA(DisplayName = "Silver voxel"),
    LIGHT_GREY = 132             UMETA(DisplayName = "Light Grey voxel"),
    DARK_GREY = 133              UMETA(DisplayName = "Dark Grey voxel"),
    SLATE = 134                  UMETA(DisplayName = "Slate voxel"),
    STONE = 135                  UMETA(DisplayName = "Stone voxel"),
    SMOKE_GREY = 136             UMETA(DisplayName = "Smoke Grey voxel"),
    PEWTER = 137                 UMETA(DisplayName = "Pewter voxel"),
    IRON = 138                   UMETA(DisplayName = "Iron voxel"),
    NICKEL = 139                 UMETA(DisplayName = "Nickel voxel"),
    ASH_GREY = 140               UMETA(DisplayName = "Ash Grey voxel"),
    GUNMETAL = 141               UMETA(DisplayName = "Gunmetal voxel"),
    PLATINUM = 142               UMETA(DisplayName = "Platinum voxel"),
    STEEL = 143                  UMETA(DisplayName = "Steel voxel"),
    CONCRETE = 144               UMETA(DisplayName = "Concrete voxel"),
    GRAPHITE = 145               UMETA(DisplayName = "Graphite voxel"),
    BATTLESHIP_GREY = 146        UMETA(DisplayName = "Battleship Grey voxel"),
    STORM_GREY = 147             UMETA(DisplayName = "Storm Grey voxel"),
    DOVE_GREY = 148              UMETA(DisplayName = "Dove Grey voxel"),
    FOSSIL = 149                 UMETA(DisplayName = "Fossil voxel"),

    // 150-169: Pastel Colors
    PASTEL_PINK = 150            UMETA(DisplayName = "Pastel Pink voxel"),
    PASTEL_BLUE = 151            UMETA(DisplayName = "Pastel Blue voxel"),
    PASTEL_GREEN = 152           UMETA(DisplayName = "Pastel Green voxel"),
    PASTEL_YELLOW = 153          UMETA(DisplayName = "Pastel Yellow voxel"),
    PASTEL_LAVENDER = 154        UMETA(DisplayName = "Pastel Lavender voxel"),
	PASTEL_ORANGE = 155          UMETA(DisplayName = "Pastel Orange voxel"),
    PASTEL_PURPLE = 156          UMETA(DisplayName = "Pastel Purple voxel"),
    PASTEL_MINT = 157            UMETA(DisplayName = "Pastel Mint voxel"),
    PASTEL_PEACH = 158           UMETA(DisplayName = "Pastel Peach voxel"),
    PASTEL_CORAL = 159           UMETA(DisplayName = "Pastel Coral voxel"),
    PASTEL_LILAC = 160           UMETA(DisplayName = "Pastel Lilac voxel"),
    PASTEL_TURQUOISE = 161       UMETA(DisplayName = "Pastel Turquoise voxel"),
    PASTEL_MAUVE = 162           UMETA(DisplayName = "Pastel Mauve voxel"),
    PASTEL_SAGE = 163            UMETA(DisplayName = "Pastel Sage voxel"),
    PASTEL_ROSE = 164            UMETA(DisplayName = "Pastel Rose voxel"),

    // 165-184: Metallic and Iridescent Colors
    METALLIC_SILVER = 165        UMETA(DisplayName = "Metallic Silver voxel"),
    METALLIC_GOLD = 166          UMETA(DisplayName = "Metallic Gold voxel"),
    METALLIC_COPPER = 167        UMETA(DisplayName = "Metallic Copper voxel"),
    METALLIC_BRONZE = 168        UMETA(DisplayName = "Metallic Bronze voxel"),
    METALLIC_ROSE_GOLD = 169     UMETA(DisplayName = "Metallic Rose Gold voxel"),
    IRIDESCENT_PEARL = 170       UMETA(DisplayName = "Iridescent Pearl voxel"),
    IRIDESCENT_BLUE = 171        UMETA(DisplayName = "Iridescent Blue voxel"),
    IRIDESCENT_GREEN = 172       UMETA(DisplayName = "Iridescent Green voxel"),
    CHROME = 173                 UMETA(DisplayName = "Chrome voxel"),
    METALLIC_PLATINUM = 174      UMETA(DisplayName = "Metallic Platinum voxel"),

    // 175-194: Neon and Vibrant Colors
    NEON_GREEN = 175             UMETA(DisplayName = "Neon Green voxel"),
    NEON_PINK = 176              UMETA(DisplayName = "Neon Pink voxel"),
    NEON_BLUE = 177              UMETA(DisplayName = "Neon Blue voxel"),
    NEON_ORANGE = 178            UMETA(DisplayName = "Neon Orange voxel"),
    NEON_YELLOW = 179            UMETA(DisplayName = "Neon Yellow voxel"),
    ELECTRIC_BLUE = 180          UMETA(DisplayName = "Electric Blue voxel"),
    ELECTRIC_GREEN = 181         UMETA(DisplayName = "Electric Green voxel"),
    HOT_PINK = 182               UMETA(DisplayName = "Hot Pink voxel"),
    FLUORESCENT_GREEN = 183      UMETA(DisplayName = "Fluorescent Green voxel"),
    FLUORESCENT_YELLOW = 184     UMETA(DisplayName = "Fluorescent Yellow voxel"),

    // 185-204: Earth and Natural Tones
    TERRA_COTTA = 185            UMETA(DisplayName = "Terra Cotta voxel"),
    DESERT_SAND = 186            UMETA(DisplayName = "Desert Sand voxel"),
    CLAY = 187                   UMETA(DisplayName = "Clay voxel"),
    CLAY_RED = 188               UMETA(DisplayName = "Clay Red voxel"),
    MUDDY_GREEN = 189            UMETA(DisplayName = "Muddy Green voxel"),
    CLAY_BROWN = 190             UMETA(DisplayName = "Clay Brown voxel"),
    DESERT_KHAKI = 191           UMETA(DisplayName = "Desert Khaki voxel"),
    MOSS = 192                   UMETA(DisplayName = "Moss voxel"),
    CLAY_GREY = 193              UMETA(DisplayName = "Clay Grey voxel"),
    RIVER_ROCK = 194             UMETA(DisplayName = "River Rock voxel"),

    // 195-214: Exotic and Unusual Colors
    MALACHITE = 195              UMETA(DisplayName = "Malachite voxel"),
    LAPIS_LAZULI = 196           UMETA(DisplayName = "Lapis Lazuli voxel"),
    TURQUOISE_STONE = 197        UMETA(DisplayName = "Turquoise Stone voxel"),
    CORAL_STONE = 198            UMETA(DisplayName = "Coral Stone voxel"),
    AMBER_STONE = 199            UMETA(DisplayName = "Amber Stone voxel"),
    OBSIDIAN = 200               UMETA(DisplayName = "Obsidian voxel"),
    ONYX = 201                   UMETA(DisplayName = "Onyx voxel"),
    JADE = 202                   UMETA(DisplayName = "Jade voxel"),
    TOPAZ = 203                  UMETA(DisplayName = "Topaz voxel"),
    OPAL = 204                   UMETA(DisplayName = "Opal voxel"),

    // 205-224: Special and Rare Colors
    ULTRAVIOLET = 205            UMETA(DisplayName = "Ultraviolet voxel"),
    INFRARED = 206               UMETA(DisplayName = "Infrared voxel"),
    PLASMA_BLUE = 207            UMETA(DisplayName = "Plasma Blue voxel"),
    RADIATION_GREEN = 208        UMETA(DisplayName = "Radiation Green voxel"),
    GHOST_WHITE = 209            UMETA(DisplayName = "Ghost White voxel"),
    TRANSPARENT_WHITE = 210            UMETA(DisplayName = "Transparent voxel"),
    HOLOGRAPHIC = 211            UMETA(DisplayName = "Holographic voxel"),
    PRISMATIC = 212              UMETA(DisplayName = "Prismatic voxel"),
    LUMINESCENT_GREEN = 213      UMETA(DisplayName = "Luminescent Green voxel"),
    BIOLUMINESCENT = 214         UMETA(DisplayName = "Bioluminescent voxel"),

    // 215-234: Complex Blended Colors
    RUST_TEAL = 215              UMETA(DisplayName = "Rust Teal voxel"),
    BURNT_ORANGE_GREEN = 216     UMETA(DisplayName = "Burnt Orange Green voxel"),
    FOREST_LAVENDER = 217        UMETA(DisplayName = "Forest Lavender voxel"),
    STORM_BLUE = 218             UMETA(DisplayName = "Storm Blue voxel"),
    SUNSET_ORANGE = 219          UMETA(DisplayName = "Sunset Orange voxel"),
    DEEP_SEA_GREEN = 220         UMETA(DisplayName = "Deep Sea Green voxel"),
    WINE_RED = 221               UMETA(DisplayName = "Wine Red voxel"),
    DESERT_BLUE = 222            UMETA(DisplayName = "Desert Blue voxel"),
    MOSS_COPPER = 223            UMETA(DisplayName = "Moss Copper voxel"),
    TWILIGHT_PURPLE = 224        UMETA(DisplayName = "Twilight Purple voxel"),

    // 225-244: Soft and Muted Colors
    SOFT_CREAM = 225             UMETA(DisplayName = "Soft Cream voxel"),
    SOFT_MINT = 226              UMETA(DisplayName = "Soft Mint voxel"),
    SOFT_LAVENDER = 227          UMETA(DisplayName = "Soft Lavender voxel"),
    SOFT_PEACH = 228             UMETA(DisplayName = "Soft Peach voxel"),
    SOFT_ROSE = 229              UMETA(DisplayName = "Soft Rose voxel"),
    SOFT_BLUE = 230              UMETA(DisplayName = "Soft Blue voxel"),
    SOFT_YELLOW = 231            UMETA(DisplayName = "Soft Yellow voxel"),
    SOFT_GREEN = 232             UMETA(DisplayName = "Soft Green voxel"),
    SOFT_BROWN = 233             UMETA(DisplayName = "Soft Brown voxel"),
    SOFT_GREY = 234              UMETA(DisplayName = "Soft Grey voxel"),
	SOFT_ORANGE = 235            UMETA(DisplayName = "Soft Orange voxel"),
	SOFT_MAGENTA = 236           UMETA(DisplayName = "Soft Magenta voxel"),
	SOFT_TEAL = 237				 UMETA(DisplayName = "Soft Teal voxel"),
	SOFT_MANGO = 238             UMETA(DisplayName = "Soft Mango voxel"),
	SOFT_GRAPE = 239             UMETA(DisplayName = "Soft Grave voxel"),
	SOFT_KIWI = 240				 UMETA(DisplayName = "Soft Kiwi voxel"),
	SOFT_SKY = 241				 UMETA(DisplayName = "Soft Sky Voxel"),
	SOFT_PINK = 242				 UMETA(DisplayName = "Soft Pink voxel"),
	SOFT_CHARCOAL = 243			 UMETA(DisplayName = "Soft Charcoal voxel"),
	SOFT_SLATE = 244			 UMETA(DisplayName = "Soft Slate voxel"),

    // 245-254: Experimental and Unique Colors
    QUANTUM_BLUE = 245           UMETA(DisplayName = "Quantum Blue voxel"),
    VOID_BLACK = 246             UMETA(DisplayName = "Void Black voxel"),
    QUANTUM_GREEN = 247          UMETA(DisplayName = "Quantum Green voxel"),
    PARADOX_PURPLE = 248         UMETA(DisplayName = "Paradox Purple voxel"),
    ANOMALY_RED = 249            UMETA(DisplayName = "Anomaly Red voxel"),
    SINGULARITY_WHITE = 250      UMETA(DisplayName = "Singularity White voxel"),
    CHAOS_GREY = 251             UMETA(DisplayName = "Chaos Grey voxel"),
    ENTROPY_YELLOW = 252         UMETA(DisplayName = "Entropy Yellow voxel"),
    PROBABILITY_BLUE = 253       UMETA(DisplayName = "Probability Blue voxel"),
    UNCERTAINTY_GREEN = 254      UMETA(DisplayName = "Uncertainty Green voxel"),

    // Final color
    FINAL_COLOR = 255            UMETA(DisplayName = "Final Color voxel"),
};